[package]
name = "era_automation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.17.2", features = ["dynamic_linking"]}
libnoise = "1.2.0"
rand = "0.9.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
